---
# Grafana 설치 및 구성 태스크
# 이 파일은 Grafana 서버의 설치와 기본 설정을 담당합니다

- name: "Grafana GPG 키 추가"
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
  become: true

- name: "Grafana 저장소 추가"
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: "grafana"
  become: true

- name: "Grafana 설치"
  apt:
    name: "grafana"
    state: present
    update_cache: yes
  become: true

- name: "Grafana 설정 디렉토리 생성"
  file:
    path: "/etc/grafana/provisioning"
    state: directory
    mode: "0755"
    owner: "grafana"
    group: "grafana"
  become: true

- name: "Grafana 메인 설정 파일 생성"
  template:
    src: "grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
    owner: "grafana"
    group: "grafana"
    mode: "0644"
  become: true
  notify: "Grafana 재시작"

- name: "Grafana 데이터베이스 설정"
  template:
    src: "database.yml.j2"
    dest: "/etc/grafana/provisioning/datasources/database.yml"
    owner: "grafana"
    group: "grafana"
    mode: "0644"
  become: true
  notify: "Grafana 재시작"

- name: "Grafana SMTP 설정"
  template:
    src: "smtp.yml.j2"
    dest: "/etc/grafana/provisioning/notifiers/smtp.yml"
    owner: "grafana"
    group: "grafana"
    mode: "0644"
  become: true
  when: smtp_enabled
  notify: "Grafana 재시작"

- name: "Grafana LDAP 설정"
  template:
    src: "ldap.toml.j2"
    dest: "/etc/grafana/ldap.toml"
    owner: "grafana"
    group: "grafana"
    mode: "0644"
  become: true
  when: ldap_enabled
  notify: "Grafana 재시작"

- name: "Grafana 서비스 활성화 및 시작"
  systemd:
    name: "grafana-server"
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: "Grafana 상태 확인"
  uri:
    url: "http://localhost:{{ grafana_port }}/api/health"
    method: GET
  register: grafana_health
  retries: 10
  delay: 10
  until: grafana_health.status == 200

- name: "Grafana 관리자 계정 설정"
  uri:
    url: "http://localhost:{{ grafana_port }}/api/admin/users"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ admin_user }}"
      email: "admin@{{ grafana_domain }}"
      login: "{{ admin_user }}"
      password: "{{ admin_password }}"  # 하드코딩된 비밀번호
      orgId: 1
      isAdmin: true
  register: admin_user_result
  retries: 3
  delay: 5
  until: admin_user_result.status == 200 or "already exists" in admin_user_result.msg | default("")

- name: "Grafana 플러그인 설치"
  command: "grafana-cli plugins install {{ item }}"
  become: true
  become_user: "grafana"
  loop: "{{ grafana_plugins }}"
  notify: "Grafana 재시작"
